### ISSUE TITLE
Error: USB Stick not detected for logging : retry:

### ISSUE THREAD

**Issue by HHZZUUJH** [liketohear/liketohear#7]
Extract from the instruction:

https://github.com/liketohear/liketohear/wiki

Install the #liketohear extensions and control app on your Raspberry Pi:
1.	Plug in your USB-stick (otherwise the app won't work)

After the start this error occurs:

USB Stick not detected for logging : retry:

I connected an empty usb-stick. But this is not recognized. Should this one be mounted? There is no command implemented in the software.

**Comment by TobiBruns** [comment]
This is because currently sandisc will only be scanned.  should have been in the documentation see #1 by @pgys

Try to find your usb stick with command. 

`$ ls -l /dev/disk/by-id`

and replace san disc by your device name in resources/automount.sh:

`sudo mount -o uid=$UID '/dev/'$(ls -l /dev/disk/by-id | grep SanDisk | tail -1 | awk -F'/' '{print $3}') /media`

need to run resources/install.sh after this again

**Comment by HHZZUUJH** [comment]
solved with a SanDisk USB stick

**Comment by TobiBruns** [comment]
Great!! Thank you for your comments and report's. This will help the ones that might have similar problems.
